[package]
name = "mysqlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "20.0.0"
once_cell = "1.13.0"
tracing = "0.1.40"